### ISSUE TITLE
Error from `npm start` 

### ISSUE THREAD

**Issue by adamski** [alinz/example-react-native-redux#16]
I am getting the following error log from `npm start`:

```
1 verbose cli [ '/usr/local/Cellar/node/5.5.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.5.3
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Counter@0.0.1~prestart: Counter@0.0.1
6 silly lifecycle Counter@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle Counter@0.0.1~start: Counter@0.0.1
8 verbose lifecycle Counter@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle Counter@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/adamelemental/dev/react-projects/example-react-native-redux/Counter/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/adamelemental/dev/SDKs/android-sdk/platform-tools
10 verbose lifecycle Counter@0.0.1~start: CWD: /Users/adamelemental/dev/react-projects/example-react-native-redux/Counter
11 silly lifecycle Counter@0.0.1~start: Args: [ '-c', 'react-native start' ]
12 silly lifecycle Counter@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle Counter@0.0.1~start: Failed to exec start script
14 verbose stack Error: Counter@0.0.1 start: `react-native start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid Counter@0.0.1
16 verbose cwd /Users/adamelemental/dev/react-projects/example-react-native-redux/Counter
17 error Darwin 15.0.0
18 error argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.5.0
20 error npm  v3.5.3
21 error code ELIFECYCLE
22 error Counter@0.0.1 start: `react-native start`
22 error Exit status 1
23 error Failed at the Counter@0.0.1 start script 'react-native start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Counter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     react-native start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Counter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Counter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

However running `react-native start` from Counter folder works fine.

**Comment by alinz** [comment]
@adamski where did you run this command?

**Comment by adamski** [comment]
From within the `Counter` folder.

**Comment by alinz** [comment]
remove node_modules and run npm install again and see if it works.

**Comment by alinz** [comment]
@adamski did you manage to solve this issue, if so, would you provide some detail how?

**Comment by adamski** [comment]
No, not managed to solve it ... as I said I can get around it by running `react-native start`

I tried the steps you suggested but no luck.

**Comment by alinz** [comment]
@adamski don't you need `run` command? I don't think you can do this `npm start`. What you have to do is `npm run start`. `start` is one of the `package.json`'s script that I added which is exactly the same as `react-native start`.

**Comment by adamski** [comment]
Same issue with `npm run start` …

**Comment by alinz** [comment]
@adamski I have upgraded the code to latests. Can you try again. and please tell me what version of npm, node and watchman are you using?

**Comment by alinz** [comment]
@adamski I'm closing this issue. if you still have that issue reopen it.

**Comment by hadynz** [comment]
+1 

Getting the same issue with a vanilla installation of react native
