### ISSUE TITLE
Build failed with error: Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by Creemli** [alinz/example-react-native-redux#9]
When I clone this project from Github and then run "npm install".
After that I open the project with XCode, and build it, here is the error:

<code><pre>
react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/apple/Library/Developer/Xcode/DerivedData/Counter-faxpmupnkzagayfuceclbszanytu/Build/Products/Debug-iphonesimulator/Counter.app/main.jsbundle --assets-dest /Users/apple/Library/Developer/Xcode/DerivedData/Counter-faxpmupnkzagayfuceclbszanytu/Build/Products/Debug-iphonesimulator/Counter.app
bundle: Created ReactPackager
uncaught error Error: ReferenceError: [BABEL] /Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/redux/lib/index.js: Unknown option: /Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/redux/.babelrc.stage
    at Logger.error (/Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/react-native/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.addConfig (/Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/react-native/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/react-native/node_modules/babel-core/lib/transformation/file/index.js:121:22)
    at Pipeline.transform (/Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/react-native/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transform (/Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/react-native/packager/transformer.js:56:24)
TransformError: /Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/redux/lib/index.js: [BABEL] /Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/redux/lib/index.js: Unknown option: /Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/redux/.babelrc.stage
See logs /var/folders/p9/6nq91lt97xbd803y6wlq2m9w0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/apple/Desktop/Github/example-react-native-redux/Counter/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Command /bin/sh failed with exit code 1

</pre></code>

Could you please have a look at this?
I am learning how to import Redux into my React-Native Project...

**Comment by alinz** [comment]
@Creemli I have updated react-redux versioning. Please clone from master again and remove `node_module` folder inside `Counter` folder. Once you done that run `npm install` again and see if this work.

**Comment by alinz** [comment]
@Creemli one more thing, make sure to run `npm run clean` once the `npm install` finishes. There are still some `babelrc` files remains in redux side modules

**Comment by Creemli** [comment]
Wow, it works!! Thanks a lot!

So the reason is about the ".babelrc " files??

**Comment by alinz** [comment]
Glad that it works,

babel6 is being used in react-native 0.16 and above and all modules written babel5 needs to be updated in order to work properly with react-native.

**Comment by Creemli** [comment]
Thank you very much.  
Actually you have announced that running <code>npm run clean</code> is necessary, but I missed it carelessly. 
Wish the next one would note that~~
